### ISSUE TITLE
Update nokogiri >= 1.11.4

### ISSUE THREAD

**Issue by pl-aknight** [q2ebanking/boa-constrictor#104]
Dependabot discovered a security vulnerability in `nokogiri`:
https://github.com/q2ebanking/boa-constrictor/security/dependabot/docs/Gemfile.lock/nokogiri/open

Unfortunately, GitHub Pages support only up to 1.11.2 at the time of opening this issue:
https://pages.github.com/versions/

Once GitHub Pages supports an updated version of the package, we should update the Gemfile for the Boa Constrictor doc site.

**Comment by pl-aknight** [comment]
I created a GitHub Support ticket: https://support.github.com/ticket/personal/0/1178608

**Comment by AndyLPK247** [comment]
It looks like GitHub Pages updated their supported package versions!
