### ISSUE TITLE
Running multiple tasks in a single AttemptsTo block

### ISSUE THREAD

**Issue by thePantz** [q2ebanking/boa-constrictor#107]
Hello! and thank you for the repo! Really great to see Screenplay making it into the .NET space. 

Coming from SerenityBDD, one feature that I'm missing the most in this repo is being able to pass in multiple tasks in a single `AttemptsTo()` call.

In other words, I want to be able to turn this:

```
actor.AttemptsTo(SendKeys.To(LoginPage.UserField, userName));
actor.AttemptsTo(SendKeys.To(LoginPage.PasswordField, password));
actor.AttemptsTo(Click.On(LoginPage.LogInButton));
```

into this:

```
actor.AttemptsTo(
    SendKeys.To(LoginPage.UserField, userName),
    SendKeys.To(LoginPage.PasswordField, password),
    Click.On(LoginPage.LogInButton)
);
```

Saves me a few keystrokes, typing out `actor.AttemptsTo()` over and over again and it's a little more readable imo.

The implementation would look something like this:

```
public class Actor {

...

public void AttemptsTo(params ITask[] tasks) {
    foreach(ITask task in tasks) {
        AttemptsTo(task);
    }
}
```

**Comment by AndyLPK247** [comment]
Hi @thePantz! Thanks.

We have a special Task named `RunTasks` that lets you combine multiple tasks into one task:
https://github.com/q2ebanking/boa-constrictor/blob/main/Boa.Constrictor/Screenplay/Tasks/RunTasks.cs

Usage:

```csharp
Actor.AttemptsTo(
    RunTasks.InOrder(
        SendKeys.To(LoginPage.UserField, userName),
        SendKeys.To(LoginPage.PasswordField, password),
        Click.On(LoginPage.LogInButton)
    )
);
```

`RunTasks` creates a new Task object, which means you can create it one place and call it elsewhere. You could also define custom Tasks as a sequence of existing Tasks without needing to create an entirely new class.

However, I recognize the value in the simpler syntax you recommended for in-line calls. `RunTasks.InOrder(...)` adds extra verbiage without conveying valuable meaning in that case.

I'll chat about your suggestion with my team next week. I don't foresee any problems with implementing it, and it would be a small code change. You are welcome to open a pull request for it, too!

**Comment by thePantz** [comment]
Aha! I wasn't aware of `RunTasks`, this will really useful! In the world of Serenity we call this an 'Anonymous Task'. 

I'm guessing this is a common usage:

```
public static ITask Login(string userName, string password) {
    return RunTasks.InOrder(
        SendKeys.To(LoginPage.UserField, userName),
        SendKeys.To(LoginPage.PasswordField, password),
        Click.On(LoginPage.LogInButton)
    );
}
```

Like you said, the simpler syntax provides value. I'll submit a PR! Thanks!
