### ISSUE TITLE
GeckoDriver MoveToElement

### ISSUE THREAD

**Issue by Maelgwyn** [q2ebanking/boa-constrictor#114]
Hey,

I'm using gecko driver for a number of tests and it doesn't seem to support MoveToElement (probably more).

A number of the tasks use this and I end up with error OpenQA.Selenium.MoveTargetOutOfBoundsException.

I can write my own tasks to run javascript to do the scroll but it's a bit annoying that I can't use Boa's inbuilt tasks.

Am I just missing something?

**Comment by pl-aknight** [comment]
Hi @Maelgwyn! That sounds annoying.

Unfortunately, my team and I don't use Boa Constrictor with Firefox / geckodriver. Could you please provide more info about your testing environment?

- Operating system
- Firefox version
- geckodriver version

Please also list all the Interactions that you have discovered with this problem.

We might need to add special logic to support Firefox / geckodriver. Every browser has its quirks.

Thanks!

**Comment by Maelgwyn** [comment]
Operating System: Windows and Linux
Firefox Version: 89.0.1
Gecko Driver version: 0.29.1

Both Click and Hover on line 45 use MoveToElement.

The ScrollToElement task uses javascript to move the element into view. So maybe it just a matter of updating Click and Hover to use that if needed.

**Comment by pl-aknight** [comment]
Thanks for the info! We will take a look soon.

**Comment by thePantz** [comment]
This is a [known issue](https://github.com/mozilla/geckodriver/issues/776) with GekoDriver. Essentially they are waiting on a webdriver spec change in order to support. The recommendation is to use javascript instead: 

```
WebElement element = driver.findElement(locator);
((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView(true);", element);
```
