### ISSUE TITLE
Add IsNullOrWhitespace Condition

### ISSUE THREAD

**Issue by SabotageAndi** [q2ebanking/boa-constrictor#124]
I just needed an `IsNullOrWhitespace` condition, because I had to wait until an HTML attribute was available.

Would you be interested in adding it to boa itself? I can submit a PR with it later.

**Comment by pl-aknight** [comment]
@SabotageAndi - I'm a bit swamped this week. Feel free to open a pull request, and I'll review (and hopefully approve) it. Thanks!
