### ISSUE TITLE
IsDateAsStringTest are failing with "was not recognized as a valid DateTime"

### ISSUE THREAD

**Issue by SabotageAndi** [q2ebanking/boa-constrictor#13]
With commit "17022664772fc071114eef81eb820f5c2535180c" two tests in IsDateAsStringTests are failing

![image](https://user-images.githubusercontent.com/859801/96579176-b42bc200-12d6-11eb-9678-bf4b1b64eb2c.png)
![image](https://user-images.githubusercontent.com/859801/96579225-c9a0ec00-12d6-11eb-98b9-0cd35cbfc83c.png)

I assume this is because I am running on german region settings.

**Comment by aknight-pl** [comment]
Thanks, @SabotageAndi ! I'll take a look at this within the week.

**Comment by SabotageAndi** [comment]
No need to stress. I noticed this during looking at the code. If I would know the right solution, I would have send already a PR for it.

**Comment by AndyLPK247** [comment]
I've thought about this up and down, and I don't think _IsDateAsString_ is an appropriate Condition to include in this open source project. _IsDateAsString_ is meant to be a convenience Condition. It does not handle different formats/cultures. Making it handle different formats/cultures would defeat its simplicity. We should remove it.
