### ISSUE TITLE
Nuget package doesn't include XML docs

### ISSUE THREAD

**Issue by shack05** [q2ebanking/boa-constrictor#15]
The current Nuget package (0.2.2) doesn't include the XML documentation:

![image](https://user-images.githubusercontent.com/25411107/96943840-f9ddca00-1524-11eb-9058-a39e2803717b.png)

Assuming you want the docs included, they can be enabled by adding `<GenerateDocumentationFile>true</GenerateDocumentationFile>` to the `<PropertyGroup>` in the csproj file.

However, after enabling the above, quite a few warnings of different types are raised such as codes 1591, 1572, 1573, ...
Specific codes can be ignored at a project level by adding another `PropertyGroup` item: `<NoWarn>$(NoWarn);1591;1572;1573</NoWarn>` 

If you like I can submit a PR, but I'm not sure how you would like the warnings to be handled.

**Comment by AndyLPK247** [comment]
@shack05 great catch! Thanks for opening this issue. I'll take a look at the warning codes soon.

**Comment by AndyLPK247** [comment]
I took a look at the warnings, and I'd like to resolve them. I'm making fixes now.

**Comment by AndyLPK247** [comment]
I created a PR for the fix! It'll probably get reviewed next week. Then, we can release a new package version.
