### ISSUE TITLE
Rewrite NuGet Push GitHub Action

### ISSUE THREAD

**Issue by AutomationPanda** [q2ebanking/boa-constrictor#186]
Boa Constrictor uses a GitHub Action to automatically build and publish a new NuGet package every time the version in the `.csproj` file changes in the `main` branch. The GitHub Action is located here:
https://github.com/q2ebanking/boa-constrictor/blob/main/.github/workflows/nuget-push.yml

It relies on another GitHub Action named `publish-nuget`:
https://github.com/brandedoutcast/publish-nuget

Unfortunately, it appears that the author of this GitHub Action has abandoned it. It would be nice to write our own GitHub Action to do the same thing. That way, we don't depend on someone's abandoned project. Here are some helpful links:

- https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-push
- https://github.com/brandedoutcast/publish-nuget/issues/21#issuecomment-801922295
- https://github.com/brandedoutcast/publish-nuget/issues/58

Our new action should do all the same things as the original except handle symbols packages. It doesn't need to be generic enough to handle any package, but it should try to detect version changes and tag commits.

**Comment by CoffeeAtBedtime** [comment]
I noticed the suggestion on `brandedoutcast`'s repo for the archived nuget-push action...
> You can replicate the functionality of this action & much more by using the offical tools like dotnet CLI or GitHub CLI etc.

The GitHub CLI can be called inside a GitHub action https://docs.github.com/en/actions/using-workflows/using-github-cli-in-workflows and a lot of handy commands already https://cli.github.com/manual/

**Comment by AutomationPanda** [comment]
Right on, @CoffeeAtBedtime! I think the `dotnet nuget push` command's `--skip-duplicate` option can help us here.
