### ISSUE TITLE
Explore Polly

### ISSUE THREAD

**Issue by AndyLPK247** [q2ebanking/boa-constrictor#19]
[Polly](https://github.com/App-vNext/Polly) is a .NET resilience and transient-fault-handling library that allows developers to express policies such as Retry, Circuit Breaker, Timeout, Bulkhead Isolation, and Fallback in a fluent and thread-safe manner.

**Should we use Polly for Boa Constrictor's waiting and retries?** Maybe. Let's discuss that here in this issue.

**Comment by pl-aknight** [comment]
Polly looks like a great package, but I think it's overkill for Boa Constrictor's needs.
