### ISSUE TITLE
[FEATURE]: Better logging support for xUnit

### ISSUE THREAD

**Issue by thePantz** [q2ebanking/boa-constrictor#227]
### Description

XUnit v2 does not support the use of `Console`, `Debug`, `Trace`

> If you used xUnit.net 1.x, you may have previously been writing output to Console, Debug, or Trace. When xUnit.net v2 shipped with parallelization turned on by default, this output capture mechanism was no longer appropriate; it is impossible to know which of the many tests that could be running in parallel were responsible for writing to those shared resources.

This means that Boa.Constrictors built in `ConsoleLogger` will not work for xUnit. 
I suggest we implement a new logger that will work with xUnits logging interface(s) as described here: https://xunit.net/docs/capturing-output

### Alternatives

Switching to NUnit/MsTest

### Anything else?

Should be pretty straight forward to implement support for `ITestOutputHelper`. It functions similarly to `Console` but would require an instance provided by xUnit.

There may be some limitations with setting up Actors in [Class Fixtures](https://xunit.net/docs/shared-context#class-fixture) since they won't have access to `ITestOutputHelper` from that context

### Commitments

- [X] I agree to follow Boa Constrictor's [Code of Conduct](https://q2ebanking.github.io/boa-constrictor/contributing/code-of-conduct/).
- [X] I want to work on this issue myself. (This is voluntary, not required.)

**Comment by thePantz** [comment]
The solution to this is the following:

```
public class XUnitLogger : AbstractLogger
{
      private readonly ITestOutputHelper output;

      public XUnitLogger(ITestOutputHelper output, LogSeverity severity = LogSeverity.Trace)
          :base(severity)
      {
          this.output = output;
      }

      public override void Close()
      {
          // This logger needs no closing
      }

      protected override void LogRaw(string message, LogSeverity severity = LogSeverity.Info)
      {
          if(severity >= LowestSeverity)
              output.WriteLine(message);
      }
}

public class MyTest
{
        private readonly ITestOutputHelper output;
        public MyTest(ITestOutputHelper output)
        { 
            this.output = output;
        }

        [Fact]
        public void EditIcon_ShouldPutRowInEditMode()
        {
            var test = new Actor("Customer", new XUnitLogger(output));
        }
}
```

Given the recent architecture changes, where should I place this? At first I considered placing this under `Boa.Constrictor.Screenplay` however it would require adding an xUnit dependency. Would it be more appropriate to start a `Boa.Constrictor.xUnit` project?

**Comment by AutomationPanda** [comment]
@thePantz, this is good stuff. You're absolutely right about the dependency issue. I think I agree with your assessment that we'd want a separate project and package for xUnit to support this.

My questions for you:

- Is this something you'd want to do?
- Do you want this to be part of the main Boa Constrictor repository?

I'd love to collaborate with you on this if you're up for the challenge!

**Comment by thePantz** [comment]
Yes! I would be happy to contribute! I figure it's a general enough use case that will be useful to others. 

Although, I noticed #20 the other day and was wondering if this is still valuable or if it will soon be obsolete

**Comment by AutomationPanda** [comment]
#20 is still valid but not planned at the moment. I'd say move forward with this xUnit logger for now. We can change things in the future.

**Comment by AutomationPanda** [comment]
@thePantz feel free to fork the repository, get working, and send a pull request!

**Comment by AutomationPanda** [comment]
(I'm here to answer questions and offer help along the way if you need it, too!)

**Comment by AutomationPanda** [comment]
This work was completed as part of #248 !
