### ISSUE TITLE
[FEATURE]: Playwright

### ISSUE THREAD

**Issue by georgait** [q2ebanking/boa-constrictor#239]
### Description

Are there any plans to add playwright? 

### Commitments

- [X] I agree to follow Boa Constrictor's [Code of Conduct](https://q2ebanking.github.io/boa-constrictor/contributing/code-of-conduct/).
- [ ] I want to work on this issue myself. (This is voluntary, not required.)

**Comment by pl-shernandez** [comment]
😀 Yep https://automationpanda.com/2022/11/30/plans-for-boa-constrictor-3/

**Comment by AutomationPanda** [comment]
That's awesome, @georgait ! Please move discussion to #71 . I'll close this issue as a duplicate.
