### ISSUE TITLE
Make unit testing a required check for pull requests

### ISSUE THREAD

**Issue by AndyLPK247** [q2ebanking/boa-constrictor#25]
PR #23 added a GitHub Action to automatically run unit tests for pull requests. However, the unit test check is not "Required" like the other checks:
![Screen Shot 2020-10-23 at 6 24 31 PM](https://user-images.githubusercontent.com/17988946/97058936-24e41000-155d-11eb-9890-1cc9e2035cf7.png)

I'd like to make it required for `main`. I read this guide, but it looks like I don't have the ability to do so:
https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-required-status-checks

@dnunez32, are you able to help with this once #23 gets approved and merged? Is this just a feature that certain users don't have, or is it unavailable for the project?

**Comment by dnunez32** [comment]
Fixed
