### ISSUE TITLE
[FEATURE]: Add support for RestAssured.Net

### ISSUE THREAD

**Issue by basdijkstra** [q2ebanking/boa-constrictor#268]
### Description

As an alternative to (not a replacement of!) using RestSharp, I’d like to suggest adding support for [RestAssured.Net](https://github.com/basdijkstra/rest-assured-net) to Boa Constrictor.

I think support for a test-first library such as RestAssured.Net is a great alternative to have compared to supporting a general-purpose library like RestSharp.

### Alternatives

N/A

### Anything else?

As the creator of RestAssured.Net I’m more than happy to implement this addition myself.

In case of any required additions / improvements to RestAssured.Net for optimum integration, working on this myself will definitely streamline the process ;)

### Commitments

- [X] I agree to follow Boa Constrictor's [Code of Conduct](https://q2ebanking.github.io/boa-constrictor/contributing/code-of-conduct/).
- [X] I want to work on this issue myself. (This is voluntary, not required.)

**Comment by basdijkstra** [comment]
Pinging @AutomationPanda. Any ideas or comments on this one?

**Comment by AutomationPanda** [comment]
Hey @basdijkstra! This is a great suggestion, and we'd be happy to welcome this contribution.

**Comment by basdijkstra** [comment]
Awesome! I’ll get to work as soon as possible then. It might take me a while to send a PR but rest assured (bazinga!) I’m working on it.

**Comment by basdijkstra** [comment]
So, in order to target `netstandard2.0`, RestAssured.Net itself also needs to target `netstandard2.0`, which it doesn't at the moment. I've done a quick check to see how easy or hard it would be to change compatibility in RestAssured.Net, and it's not trivial.

I'll have a good think first about whether `netstandard2.0` compatibility is something I want to introduce.

**Comment by AutomationPanda** [comment]
Sure, no problem. Just let me know!

**Comment by basdijkstra** [comment]
I won't be able to implement this support because RestAssured.Net does not target `netstandard2.0`, and I'm not going to either:  https://github.com/basdijkstra/rest-assured-net/issues/106

Thanks for considering it, though, @AutomationPanda !

**Comment by AutomationPanda** [comment]
Understood.
