### ISSUE TITLE
Create a delivery pipeline for publishing public NuGet packages

### ISSUE THREAD

**Issue by pl-aknight** [q2ebanking/boa-constrictor#3]
The open source code is great, but people need a NuGet package if they really want to use Boa Constrictor.

Questions:

- Name? (_Boa.Constrictor_ seems good.)
- Versioning?
- How to build and release? (GitHub actions?)
- NuGet.org account?

**Comment by AndyLPK247** [comment]
It looks like we can use this GitHub action:
https://github.com/marketplace/actions/publish-nuget

We would need to make the NuGet key a secret:
https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets

**Comment by pl-aknight** [comment]
DONE! 0.3.0 is the first one using this new process: https://www.nuget.org/packages/Boa.Constrictor/0.3.0
