### ISSUE TITLE
(Possible) minor inconsistencies

### ISSUE THREAD

**Issue by shack05** [q2ebanking/boa-constrictor#36]
Hello, 

Two things that I have noticed that I thought were worth bringing to your attention:
1. The first link in the [Screenplay pattern](https://github.com/q2ebanking/boa-constrictor/blob/main/README.md#the-screenplay-pattern) section in the Readme redirects to a login page.
2. [SwitchWindowToLatest.cs](https://github.com/q2ebanking/boa-constrictor/blob/main/Boa.Constrictor/WebDriver/Tasks/SwitchWindowToLatest.cs#L4) isn't sitting in the `Boa.Constrictor` namespace like every other type.

**Comment by pl-aknight** [comment]
Great catch! I'll get these fixed today.
