### ISSUE TITLE
Add a secret for a NuGet.org API key

### ISSUE THREAD

**Issue by pl-aknight** [q2ebanking/boa-constrictor#39]
Currently, new NuGet packages are built and pushed to NuGet using a private pipeline within Q2. I want to replace that with a GitHub Action to build and push a new NuGet package every time the version is updated in the .csproj file. However, the GitHub Action will need a NuGet API key to authenticate as my NuGet.org user.

This issue covers the work to add that key as a secret to this repository. Instructions for adding secrets are here:
https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets

Please name the key `NUGET_API_KEY`. I'll send the value for the key via direct message.

**Comment by dnunez32** [comment]
Completed and duly verified.
