### ISSUE TITLE
.NET 5 Support

### ISSUE THREAD

**Issue by pl-aknight** [q2ebanking/boa-constrictor#43]
Update the .NET projects to target .NET 5. We might want to have multiple targets.

**Comment by pl-aknight** [comment]
It looks like the existing GitHub Actions don't yet support .NET 5. We can probably update them to support it. However, this isn't a priority right now.

**Comment by sparky2471** [comment]
Any thoughts about migrating to .NetCore at all?

**Comment by pl-aknight** [comment]
Boa.Constrictor targets .NET Standard 2.0, so it should support .NET Core and .NET Framework. The test projects (Example & UnitTests) target .NET Core 3.1. I thought that Boa.Constrictor would not need to explicitly have a .NET Core target because it is .NET Standard. Is there a reason for adding an explicit .NET Core target to Boa.Constrictor for versions before .NET 5?

**Comment by sparky2471** [comment]
You're absolutely right. I'm just thinking from a maintenance standpoint it's easier to support just .NETCore but I can see the benefit of keeping .NET Standard to support both. I'm working on another project where it appears they were able to get GitHub Actions to support .NET 5. I plan to take a stab at this sometime today.

**Comment by pl-aknight** [comment]
@sparky2471 that would be awesome! Let me know how it goes.

**Comment by sparky2471** [comment]
Would you mind adding me as a contributor or assign the issue to me? It won't let me assign it.

**Comment by pl-aknight** [comment]
Also, for context, we *need* to support .NET Framework for PrecisionLender / Q2.

**Comment by AndyLPK247** [comment]
Here's an article on the future of .NET Standard:
https://devblogs.microsoft.com/dotnet/the-future-of-net-standard/

It looks like we should ultimately target .NET 5 and not .NET Standard.

**Comment by AndyLPK247** [comment]
.NET Framework versions:
https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies
