### ISSUE TITLE
File drop task?

### ISSUE THREAD

**Issue by mpelley** [q2ebanking/boa-constrictor#66]
It would be nice to have a "file drop" task.  I could really use this for my tests.

**Comment by AndyLPK247** [comment]
Hi @mpelley. Could you please provide more information? Please describe the full scenario. Please point to an existing web page or upload screenshots, too.

**Comment by mpelley** [comment]
I (a novice at website testing) am writing a test for a website that has a media file upload capability.  The relevant HTML is:
```
<div class="file-drop-target">
  <label id="file" class="jss57" for="upload">Drag and drop files here, or click here to browse for the files.</label>
  <input id="upload" style="display: none;" type="file" accept=".mp3, .m4a, .wav, .ogg" multiple="">
</div>
```
This looks like:
![Screenshot](https://user-images.githubusercontent.com/61086313/104957150-99cbb800-599b-11eb-9b65-0048da2eefaa.png)

The user either clicks to open the OS's "open file" dialog or drags a file and drops it on the `<input>`.
Since I can't enter data into the OS's "open file" dialog from my test script (can I?), I was hoping to use the file drop method.
Selenium seems to have support for this.  [See this.](https://www.guru99.com/drag-drop-selenium.html)
Is it possible to directly access Selenium functions with my Actor?

**Comment by AndyLPK247** [comment]
Got it. Thanks @mpelley.

To access the Actor's WebDriver instance, make the following call:
`Actor.Using<BrowseTheWeb>().WebDriver`

If you want to make custom WebDriver-based interactions, then you can make a subclass of `IQuestion`/`AbstractWebQuestion` or `ITask`/`AbstractWebTask`. Inside the new interaction class, make calls to the Actor's WebDriver instance as you please. A great example to reference is the [Click](https://github.com/q2ebanking/boa-constrictor/blob/main/Boa.Constrictor/WebDriver/Tasks/Click.cs) task. You could create a task named `DropFile` and put the WebDriver code inside its `PerformAs` method.

I strongly recommend _against_ making direct WebDriver calls outside of interactions. Screenplay calls should be one level higher than WebDriver calls.

I'm not sure if a `DropFile` task would be appropriate to include in the Boa Constrictor package. I looked up examples of how others implemented this functionality, and it looked pretty messy. Nevertheless, if you can come up with a good, clean implementation, then please open a pull request, and I'd be happy to review it. Even if we choose not to include it in Boa Constrictor, you could still definitely use it in your own project. For example, we wrote dozens of interactions for my team's automation project that aren't included in Boa Constrictor for various reasons.

**Comment by mpelley** [comment]
Oops; the article at the link in my previous comment is for dragging one element onto another, not for dropping a file onto an element.
Since all that dropping the file does is give filename to the `<input>`, all I need to do is do a `SendKeys()` to the `<input>`.  However, the standard `SendKeys()` waits for the element to have Appearance.  This `<input>` has `style="display:none"` so it never "appears".  So, what I will do is add an option to SendKeys that doesn't wait for Appearance to be true.  That seems to work for this website.

**Comment by AndyLPK247** [comment]
Here's my recommendation for you:

Try making your own copy of `SendKeys`. Then change this line:
https://github.com/q2ebanking/boa-constrictor/blob/main/Boa.Constrictor/WebDriver/Tasks/SendKeys.cs#L153

Replace `Appearance` with `Existence`. Then, test it to see if it works. Selenium WebDriver can be finicky with appearance vs. existence. I don't know if WebDriver will let you send keys to an element that exists in the DOM but does not appear (e.g., is hidden) on the page. It might blow up. If this change does work, then I'd be okay to simply replace `Appearance` with `Existence` in the `SendKeys` interaction. That would be a one-line pull request.

(Please note that I would categorically reject a pull request that outright removes the waiting safety check.)

**Comment by pl-aknight** [comment]
@mpelley any update?

**Comment by mpelley** [comment]
I did as you suggested and it works fine for me.  I'm new to working in github, so I need to learn more before I do a "fork" and "pull" request.  I'll probably do that over the next several weeks.

**Comment by pl-aknight** [comment]
@mpelley, to make things simpler for you, I could make the change and release a new Boa Constrictor package. Could you please paste the code you wrote as a comment in this issue so that I may reference it? Thanks!

**Comment by mpelley** [comment]
I made these changes to SendKeys.cs.  The first is replacing the "Appearance" with "Existence".  The second is to fix a browser complaining when sending a zero-length string to delete stuff that wasn't there.

$ git diff Boa.Constrictor/WebDriver/Tasks/SendKeys.cs
diff --git a/Boa.Constrictor/WebDriver/Tasks/SendKeys.cs b/Boa.Constrictor/WebDriver/Tasks/SendKeys.cs
index c4d41ed..0f6cf12 100644
--- a/Boa.Constrictor/WebDriver/Tasks/SendKeys.cs
+++ b/Boa.Constrictor/WebDriver/Tasks/SendKeys.cs
@@ -150,7 +150,7 @@ namespace Boa.Constrictor.WebDriver
         public override void PerformAs(IActor actor, IWebDriver driver)
         {
             // Wait for the element to exist
-            actor.WaitsUntil(Appearance.Of(Locator), IsEqualTo.True());
+            actor.WaitsUntil(Existence.Of(Locator), IsEqualTo.True());

             // Get the element
             IWebElement element = driver.FindElement(Locator.Query);
@@ -169,14 +169,17 @@ namespace Boa.Constrictor.WebDriver
                     // One for each character in the input!
                     int length = element.GetAttribute("value").Length;

-                    // Send the backspaces
-                    string backspaces = string.Concat(Enumerable.Repeat(Keys.Backspace, length));
-                    element.SendKeys(backspaces);
-
-                    // The browser may put the cursor to the left instead of the right
-                    // Do the same thing for delete button
-                    string deletes = string.Concat(Enumerable.Repeat(Keys.Delete, length));
-                    element.SendKeys(deletes);
+                    if (length != 0)
+                                       {
+                        // Send the backspaces
+                        string backspaces = string.Concat(Enumerable.Repeat(Keys.Backspace, length));
+                        element.SendKeys(backspaces);
+
+                        // The browser may put the cursor to the left instead of the right
+                        // Do the same thing for delete button
+                        string deletes = string.Concat(Enumerable.Repeat(Keys.Delete, length));
+                        element.SendKeys(deletes);
+                    }
                 }
             }

**Comment by mpelley** [comment]
I made two changes to SendKeys.cs.  The first is near line 153 to replace `Appearance.Of` with `Existence.Of`.  The second is to fix a browser complaint about sending a zero-length string when trying to delete an empty item.  I added an `if (length==0)` around the "send the backspaces" code near lines 172-179.

I changed Click.cs by replacing `Appearance.Of` with `Existence.Of` near line 44.

I changed Clear.cs by replacing `Appearance.Of` with `Existence.Of` near line 42.

**Comment by AndyLPK247** [comment]
@mpelley, I’m finally circling back to this issue. I will have a fix for checking a zero-length string in `SendKeys` shortly. However, I’m very hesitant to replace appearance checks with existence checks.

I’d like to ask some questions:
- What browser(s) are you using?
- What string(s) did you send to the hidden input with SendKeys?
- If the web page in question is publicly available, could you please share a link? I’d like to try testing it myself.

Thanks!

**Comment by pl-aknight** [comment]
Here's the fix for the `SendKeys` zero-length clear string:
https://github.com/q2ebanking/boa-constrictor/pull/87

**Comment by pl-aknight** [comment]
Hi @mpelley! I'm checking in. Are you able to answer the 3 questions in the comment I left above? I also saw that you took a look at #87 - thanks!
