### ISSUE TITLE
Docs: Shields Metadata Badges

### ISSUE THREAD

**Issue by pl-shernandez** [q2ebanking/boa-constrictor#72]
These metadata badges might be of interest to potential users and contributors if included at the top of the project README. Perhaps things like "does it build", downloads, contributions, issues and dependencies could be added for a glanceable impression of the project state. https://shields.io/

**Comment by SabotageAndi** [comment]
I just send a PR for adding a badge for NuGet https://github.com/q2ebanking/boa-constrictor/pull/123

**Comment by AutomationPanda** [comment]
If we do this, then I'd like to make sure these badges look _good_ on the page.
