### ISSUE TITLE
Add Additional Properties to Actor

### ISSUE THREAD

**Issue by bottbott** [q2ebanking/boa-constrictor#73]
Hi there,

I was wondering what I would need to do to add additional properties to an Actor? I'd like to currently give them a username/password property, and may also want to describe them with other attributes down the road for other tests. 

I can see that there are a Name and Logger property, but as a C# novice, I'm afraid I'm not sure how to build up from the class in the Boa Constrictor NuGet package.

**Comment by pl-aknight** [comment]
According to SOLID principles, we should _not_ make changes to the `Actor` class. Instead, we should provide new Abilities and Interactions to extend what an Actor can do.

Ask yourself this: _Why_ do you want an Actor to have a username and password? What specifically do you want an Actor to be able to do with a username and password?

I'm guessing that you want an Actor to log into an application. To give it a username and password, create a new Ability. Try something like this:

```csharp
public class LogIntoApp : IAbility
{
    public string Username { get; set }
    public string Password { get; set; }

    private LogIntoApp(string username, string password)
    {
        Username = username;
        Password = password;
    }

    public static LogIntoApp As(string username, string password) =>
        new LogIntoApp(username, password);
}
```

Then, add this new Ability to an Actor:

```csharp
Actor.Can(LogIntoApp.As("YourUsername", "abc123password"));
```

To access the values from the Actor:

```csharp
string username = Actor.Using<LogIntoApp>().Username;
string password = Actor.Using<LogIntoApp>().Password;
```

You could then use these values in an interaction that performs login.

Remember, the Screenplay Pattern is designed for extending Actors to do new things without changing the Actor's code.

**Comment by bottbott** [comment]
Hi Andrew,

Thanks for your reply.

I had initially written the Login as an ITask, so I will have to give your approach a whirl. I'm still wrapping my head around the different ScreenPlay/Journey concepts. I'll have to study up a bit more on Abilities, but it's starting to make a bit of sense. 

Here was my old code and I'll shift things around to have it use the new Ability that I will describe based on your notes. 

```
    public class Login : ITask
    {
        public string Username { get; }
        public string Password { get; }

        private Login(string username, string password)
        {
            Username = username;
            Password = password;
        }

        public static Login As(string username, string password) =>
            new Login(username, password);

        public void PerformAs(IActor actor)
        {
            actor.AttemptsTo(Navigate.ToUrl(PageLogin.Url));
            actor.AttemptsTo(SendKeys.To(PageLogin.InputEmail, Username));
            actor.AttemptsTo(Click.On(PageLogin.ButtonNext));
            actor.WaitsUntil(Appearance.Of(PageLogin.ButtonNext), IsEqualTo.False());
            actor.WaitsUntil(Appearance.Of(PageLogin.ButtonSignIn), IsEqualTo.True());
            actor.AttemptsTo(SendKeys.To(PageLogin.InputPassword, Password));
            actor.AttemptsTo(Click.On(PageLogin.ButtonSignIn));
            actor.WaitsUntil(Appearance.Of(PageLogin.ButtonSignIn), IsEqualTo.False());
            actor.WaitsUntil(StaticMovement.Of(PageLogin.ButtonYes), IsEqualTo.True());
            actor.AttemptsTo(Click.On(PageLogin.ButtonYes));
        }
    }
```

**Comment by pl-aknight** [comment]
Cool! I'm going to close this issue.
