### ISSUE TITLE
Question: Static Page Classes

### ISSUE THREAD

**Issue by adamthesdet** [q2ebanking/boa-constrictor#90]
Do the pages need to be static classes?

Does it support parallel execution?

**Comment by pl-aknight** [comment]
Page classes do not necessarily need to be `static`. Page classes aren't necessary at all! You could make locators on the fly.

However, I recommend using static classes with static getter properties for locators to make locators universally accessible. Locators should effectively be immutable. Static getters mean that a new locator object will be created each time the getter is called, meaning that nobody could "change" a locator that would affect other calls to get the same locator.

If static page classes use static getters to build locator objects, then they are safe for parallel execution. So, this code would be safe:

```csharp
public static class MyPage
{
    public static IWebLocator MyElement => L("My Element", By.Id("myelement"));
}
```

However, if locator objects in a static class shared and mutable, then they could break parallel execution. For example, this code would not be safe:

```csharp
public static class MyPage
{
    public static IWebLocator MyElement = L("My Element", By.Id("myelement"));
}
```

Notice the difference between `=>` (which declares a property with a `get`) and `=` (which declares a variable with an object). In the latter example, someone could reassign the locator like this: `MyPage.MyElement = L("Other Element", By.Id("other"));`. That would be dangerous and could break logic in other threads.

@adamthesdet, please let me know if this answers your question. If it does, then please close this issue. Thanks!
